### ISSUE TITLE
SolveArtifact popup not work

### ISSUE THREAD

**Issue by Wetxius** [p3lim-wow/Inomena#3]
I think it not worked cause message changed and fragment id can't be get.
https://github.com/p3lim-wow/Inomena/blob/master/modules/elements/archaeology.lua#L42

**Comment by Wetxius** [comment]
I try to use code from wowpedia to fing string info from link.
`local _, _, Color, Ltype, Id, Enchant, Gem1, Gem2, Gem3, Gem4, Suffix, Unique, LinkLvl, reforging, Name = string.find(itemLink, "|?c?f?f?(%x*)|?H?([^:]*):?(%d+):?(%d*):?(%d*):?(%d*):?(%d*):?(%d*):?(%-?%d*):?(%-?%d*):?(%d*):?(%d*)|?h?%[?([^%[%]]*)%]?|?h?|?r?")`
It properly return  Id like 676 for pandaren.

**Comment by p3lim** [comment]
I'm a bit behind on updating this repo
